'use client'
/* eslint-disable react-hooks/set-state-in-effect */
import { Crown, Medal, Play, RotateCcw, Swords, Trophy, Wifi } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { playLearningSound, speakVietnamese } from '@/lib/learning-audio'
import { readProgress, recordMatch } from '@/lib/learning-progress'
import { CHALLENGE_AGENTS, closestChallengeAgent } from '@/lib/challenge-agents'

type Props = { courseTitle: string; courseIcon: string; lessons: readonly { title: string; goal: string }[] }
const PLAYERS = [['Bảo An','🦊',980],['Minh Khang','🐯',910],['Hà My','🐰',860],['Gia Huy','🐼',790]] as const

export function CourseArena({ courseTitle, courseIcon, lessons }: Props) {
  const initial=readProgress(), initialAgent=closestChallengeAgent(initial.elo)
  const [mode,setMode]=useState<'home'|'quiz'|'result'>('home'),[step,setStep]=useState(0),[score,setScore]=useState(0),[picked,setPicked]=useState<number|null>(null)
  const [stats,setStats]=useState(initial),[agentId,setAgentId]=useState(initialAgent.id),[outcome,setOutcome]=useState<{won:boolean;score:number;ratingChange:number;xp:number;seeds:number}|null>(null)
  useEffect(()=>{const current=readProgress();setStats(current);const requested=new URLSearchParams(window.location.search).get('agent');if(requested&&CHALLENGE_AGENTS.some(a=>a.id===requested))setAgentId(requested);else setAgentId(closestChallengeAgent(current.elo).id)},[])
  const agent=CHALLENGE_AGENTS.find(item=>item.id===agentId) || CHALLENGE_AGENTS[0]
  const questions=useMemo(()=>lessons.slice(-3).map((item,index)=>({question:`Mục tiêu phù hợp nhất với “${item.title}” là gì?`,answers:[item.goal,lessons[(index+1)%lessons.length].goal,'Làm thật nhanh mà không cần thử lại']})),[lessons])
  const q=questions[step]
  function restart(){playLearningSound('move');setStep(0);setScore(0);setPicked(null);setOutcome(null);setMode('quiz')}
  function choose(i:number){if(picked!==null)return;setPicked(i);if(i===0){setScore(v=>v+100);playLearningSound('correct');speakVietnamese('Chính xác!')}else{playLearningSound('wrong');speakVietnamese('Chưa chính xác. Bé xem đáp án màu xanh nhé.')}}
  function next(){if(step===questions.length-1){const finalScore=score,won=finalScore>=200,result=recordMatch(won,agent.elo);setStats(result.progress);setOutcome({won,score:finalScore,ratingChange:result.ratingChange,xp:result.xp,seeds:result.seeds});setMode('result');playLearningSound(won?'complete':'move');return}setStep(v=>v+1);setPicked(null);playLearningSound('move')}
  return <section id="dau-truong" className="scroll-mt-28 rounded-[32px] border border-hairline bg-[#0ec9a2] p-5 text-white shadow-lg sm:p-8" aria-labelledby="arena-title">
    {mode==='home'?<div className="grid gap-8 lg:grid-cols-[1.15fr_.85fr] lg:items-start"><div><p className="flex items-center gap-2 text-sm font-black uppercase tracking-wider text-yellow"><Swords className="h-5 w-5"/>Đấu trường cuối khóa</p><h2 id="arena-title" className="mt-3 text-3xl text-white sm:text-5xl">Thi tài {courseTitle}</h2><p className="mt-4 max-w-2xl text-lg text-white/85">Chọn một Agent luôn online. Điểm ELO thay đổi theo độ mạnh của đối thủ, không còn mức cộng trừ cố định.</p><div className="mt-5 grid max-w-xl grid-cols-3 gap-3"><Stat value={stats.matches} label="Trận"/><Stat value={stats.wins} label="Thắng"/><Stat value={stats.elo} label="ELO"/></div><h3 className="mt-6 text-xl text-white">Chọn đối thủ máy</h3><div className="mt-3 grid gap-3 sm:grid-cols-2">{CHALLENGE_AGENTS.map(item=><button key={item.id} type="button" onClick={()=>{setAgentId(item.id);playLearningSound('tap')}} className={`rounded-2xl border-2 p-3 text-left transition ${item.id===agent.id?'border-yellow bg-white text-ink':'border-white/30 bg-white/10 text-white hover:bg-white/20'}`}><div className="flex items-center gap-3"><span className="text-3xl">{item.avatar}</span><div className="flex-1"><strong className="block">{item.name}</strong><span className="text-xs opacity-75">{item.elo} ELO · {item.level}</span></div><span className="flex items-center gap-1 text-xs font-black text-green"><Wifi className="h-3 w-3"/>Online</span></div></button>)}</div><button onClick={restart} className="btn mt-5 min-h-14 bg-white px-6 text-[#087c67]"><Play className="h-5 w-5"/>Đấu với {agent.name}</button><details className="mt-4 max-w-xl rounded-2xl bg-black/10 p-4 text-sm"><summary className="cursor-pointer font-black">Quy tắc điểm và phần thưởng</summary><p className="mt-2 text-white/85">Thắng +6 đến +32 ELO; thua −4 đến −24 ELO. Thắng đối thủ mạnh được nhiều hơn. Hoàn thành trận luôn nhận phần thưởng cố gắng: thắng +30 XP/+10 Hạt, thua +8 XP/+2 Hạt.</p></details></div><Leaderboard icon={courseIcon} elo={stats.elo}/></div>:null}
    {mode==='quiz'&&q?<div className="mx-auto max-w-3xl"><div className="flex items-center gap-3"><button onClick={()=>setMode('home')} className="grid h-11 w-11 place-items-center rounded-full bg-white/15" aria-label="Thoát">×</button><span className="text-3xl" aria-hidden>{agent.avatar}</span><strong>{agent.name}</strong><div className="h-4 flex-1 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-yellow" style={{width:`${((step+1)/questions.length)*100}%`}}/></div><strong>{step+1}/{questions.length}</strong></div><div className="mt-8 rounded-3xl bg-white p-5 text-ink shadow-xl sm:p-8"><p className="text-sm font-black uppercase tracking-wider text-violet">Câu thử thách</p><h3 className="mt-3 text-2xl sm:text-3xl">{q.question}</h3><div className="mt-6 grid gap-3">{q.answers.map((a,i)=><button key={a} onClick={()=>choose(i)} className={`min-h-16 rounded-2xl border-2 p-4 text-left font-bold ${picked===null?'border-hairline hover:border-blue':i===0?'border-green bg-green-soft':picked===i?'border-coral bg-coral/10':'border-hairline opacity-55'}`}>{String.fromCharCode(65+i)}. {a}</button>)}</div>{picked!==null?<div className={`mt-5 flex items-center justify-between gap-3 rounded-2xl p-4 ${picked===0?'bg-green-soft text-green':'bg-coral/10 text-coral'}`}><strong>{picked===0?'✓ Chính xác! +100 điểm trận':'Chưa đúng — xem đáp án xanh nhé.'}</strong><button onClick={next} className="btn btn-primary">{step===questions.length-1?'Kết quả':'Tiếp tục'}</button></div>:null}</div></div>:null}
    {mode==='result'&&outcome?<div className="mx-auto max-w-2xl text-center"><Trophy className="mx-auto h-20 w-20 text-yellow"/><h2 className="mt-4 text-4xl text-white">{outcome.won?'Chiến thắng!':'Hoàn thành trận đấu!'}</h2><p className="mt-3 text-xl">Điểm trận: <strong className="text-yellow">{outcome.score}</strong> · ELO mới: <strong>{stats.elo}</strong> <span className={outcome.ratingChange>0?'text-yellow':'text-white/75'}>({outcome.ratingChange>0?'+':''}{outcome.ratingChange})</span></p><p className="mt-2 text-white/80">Bé nhận +{outcome.xp} XP và +{outcome.seeds} Hạt Mầm.</p><div className="mt-6 flex flex-wrap justify-center gap-3"><button onClick={restart} className="btn bg-white text-blue"><RotateCcw className="h-4 w-4"/>Thi lại</button><button onClick={()=>setMode('home')} className="btn border-2 border-white/50 bg-white/10 text-white">Đổi đối thủ</button></div></div>:null}
  </section>
}
function Stat({value,label}:{value:number;label:string}){return <div className="rounded-2xl bg-white/15 p-3 text-center"><strong className="block text-2xl">{value}</strong><span className="text-xs font-black uppercase text-white/70">{label}</span></div>}
function Leaderboard({icon,elo}:{icon:string;elo:number}){const rows=[...PLAYERS,['Bé',icon,elo] as const].sort((a,b)=>Number(b[2])-Number(a[2]));return <div className="rounded-3xl bg-white p-5 text-ink shadow-xl"><div className="flex items-center justify-between"><h3 className="text-2xl">Bảng xếp hạng tuần</h3><Crown className="h-9 w-9 text-yellow"/></div><ol className="mt-4 space-y-2">{rows.map((p,index)=><li key={p[0]} className={`flex items-center gap-3 rounded-2xl p-3 ${p[0]==='Bé'?'bg-yellow/20 ring-2 ring-yellow':'bg-cream/70'}`}><span className="grid h-8 w-8 place-items-center rounded-full bg-white"><Medal className="h-4 w-4"/></span><span className="text-2xl">{p[1]}</span><strong className="flex-1">{index+1}. {p[0]}</strong><span className="font-black text-blue">{p[2]}</span></li>)}</ol></div>}
