'use client'

import { Crown, Medal, Play, RotateCcw, Swords, Trophy, Users } from 'lucide-react'
import { useMemo, useState } from 'react'
import { playLearningSound, speakVietnamese } from '@/lib/learning-audio'

type Props={courseTitle:string;courseIcon:string;lessons:readonly {title:string;goal:string}[]}
const PLAYERS=[['Bảo An','🦊',980],['Minh Khang','🐯',910],['Hà My','🐰',860],['Gia Huy','🐼',790]] as const

export function CourseArena({courseTitle,courseIcon,lessons}:Props){
  const [mode,setMode]=useState<'home'|'quiz'|'result'>('home'),[step,setStep]=useState(0),[score,setScore]=useState(0),[picked,setPicked]=useState<number|null>(null)
  const questions=useMemo(()=>lessons.slice(-3).map((item,index)=>({question:`Mục tiêu phù hợp nhất với “${item.title}” là gì?`,answers:[item.goal,lessons[(index+1)%lessons.length].goal,'Làm thật nhanh mà không cần thử lại']})),[lessons])
  const q=questions[step]
  function restart(){playLearningSound('move');setStep(0);setScore(0);setPicked(null);setMode('quiz')}
  function choose(i:number){if(picked!==null)return;setPicked(i);if(i===0){setScore(v=>v+100);playLearningSound('correct');speakVietnamese('Chính xác! Bé nhận một trăm điểm kinh nghiệm.')}else{playLearningSound('wrong');speakVietnamese('Chưa chính xác. Bé hãy xem đáp án màu xanh và thử tiếp nhé.')}}
  function next(){if(step===questions.length-1){playLearningSound('complete');speakVietnamese('Chúc mừng! Bé đã hoàn thành thử thách.');return setMode('result')}playLearningSound('move');setStep(v=>v+1);setPicked(null)}
  return <section className="lg:col-span-2 rounded-[32px] border border-hairline bg-[#0ec9a2] p-5 text-white shadow-lg sm:p-8" aria-labelledby="arena-title">
    {mode==='home'?<div className="grid gap-8 lg:grid-cols-[1.15fr_.85fr] lg:items-center"><div><p className="flex items-center gap-2 text-sm font-black uppercase tracking-wider text-yellow"><Swords className="h-5 w-5"/>Đấu trường cuối khóa</p><h2 id="arena-title" className="mt-3 text-3xl text-white sm:text-5xl">Thi tài {courseTitle}</h2><p className="mt-4 max-w-2xl text-lg text-white/85">Hoàn thành thử thách, nhận điểm kinh nghiệm và so tài cùng các bạn. Chế độ luyện với Mầm Bot luôn sẵn sàng.</p><div className="mt-6 flex flex-wrap gap-3"><button onClick={restart} className="btn min-h-14 bg-white px-6 text-[#087c67]"><Play className="h-5 w-5"/>Làm bài kiểm tra</button><button onClick={restart} className="btn min-h-14 border-2 border-white/50 bg-white/10 px-6 text-white"><Users className="h-5 w-5"/>Đấu với Mầm Bot</button></div></div><Leaderboard icon={courseIcon}/></div>:null}
    {mode==='quiz'&&q?<div className="mx-auto max-w-3xl"><div className="flex items-center gap-3"><button onClick={()=>setMode('home')} className="grid h-11 w-11 place-items-center rounded-full bg-white/15" aria-label="Thoát">×</button><div className="h-4 flex-1 overflow-hidden rounded-full bg-black/10"><div className="h-full rounded-full bg-yellow" style={{width:`${((step+1)/questions.length)*100}%`}}/></div><strong>{step+1}/{questions.length}</strong></div><div className="mt-8 rounded-3xl bg-white p-5 text-ink shadow-xl sm:p-8"><p className="text-sm font-black uppercase tracking-wider text-violet">Câu thử thách</p><h3 className="mt-3 text-2xl sm:text-3xl">{q.question}</h3><div className="mt-6 grid gap-3">{q.answers.map((a,i)=><button key={a} onClick={()=>choose(i)} className={`min-h-16 rounded-2xl border-2 p-4 text-left font-bold ${picked===null?'border-hairline hover:border-blue':i===0?'border-green bg-green-soft':picked===i?'border-coral bg-coral/10':'border-hairline opacity-55'}`}>{String.fromCharCode(65+i)}. {a}</button>)}</div>{picked!==null?<div className={`mt-5 flex items-center justify-between gap-3 rounded-2xl p-4 ${picked===0?'bg-green-soft text-green':'bg-coral/10 text-coral'}`}><strong>{picked===0?'✓ Chính xác! +100 XP':'Chưa đúng — xem đáp án xanh nhé.'}</strong><button onClick={next} className="btn btn-primary">{step===questions.length-1?'Kết quả':'Tiếp tục'}</button></div>:null}</div></div>:null}
    {mode==='result'?<div className="mx-auto max-w-2xl text-center"><Trophy className="mx-auto h-20 w-20 text-yellow"/><h2 className="mt-4 text-4xl text-white">Hoàn thành thử thách!</h2><p className="mt-3 text-xl">Bé nhận <strong className="text-yellow">{score} XP</strong> và huy hiệu {courseIcon}</p><button onClick={restart} className="btn mt-6 bg-white text-blue"><RotateCcw className="h-4 w-4"/>Thi lại</button></div>:null}
  </section>
}

function Leaderboard({icon}:{icon:string}){return <div className="rounded-3xl bg-white p-5 text-ink shadow-xl"><div className="flex items-center justify-between"><h3 className="text-2xl">Bảng xếp hạng</h3><Crown className="h-9 w-9 text-yellow"/></div><ol className="mt-4 space-y-2">{PLAYERS.map(p=><li key={p[0]} className="flex items-center gap-3 rounded-2xl bg-cream/70 p-3"><span className="grid h-8 w-8 place-items-center rounded-full bg-white"><Medal className="h-4 w-4"/></span><span className="text-2xl">{p[1]}</span><strong className="flex-1">{p[0]}</strong><span className="font-black text-blue">{p[2]} XP</span></li>)}</ol><p className="mt-3 text-center text-xs text-ink/50">Hạng của bé hiện sau bài thi đầu tiên {icon}</p></div>}
