'use client'
/* eslint-disable react-hooks/set-state-in-effect */
import { CalendarDays, CheckCircle2, Flame, Gift, Trophy } from 'lucide-react'
import { useEffect, useState } from 'react'
import { playLearningSound, speakVietnamese } from '@/lib/learning-audio'

export function DailyQuests({courseSlug,completedCount}:{courseSlug:string;completedCount:number}){
  const [streak,setStreak]=useState(1),[claimed,setClaimed]=useState<string[]>([])
  useEffect(()=>{const key=`mam-quests-${courseSlug}`,today=new Date().toISOString().slice(0,10),saved=JSON.parse(localStorage.getItem(key)||'{}') as {date?:string;streak?:number;claimed?:string[]};let next=saved.streak||1;if(saved.date&&saved.date!==today){const yesterday=new Date(Date.now()-86400000).toISOString().slice(0,10);next=saved.date===yesterday?next+1:1}const todayClaims=saved.date===today?(saved.claimed||[]):[];setStreak(next);setClaimed(todayClaims);localStorage.setItem(key,JSON.stringify({date:today,streak:next,claimed:todayClaims}))},[courseSlug])
  const quests=[{id:'lesson',icon:'🎯',title:'Hoàn thành 1 bài học',value:Math.min(completedCount,1),goal:1,xp:20},{id:'explore',icon:'⭐',title:'Khám phá 3 bài trong khóa',value:Math.min(completedCount,3),goal:3,xp:50},{id:'streak',icon:'🔥',title:'Giữ chuỗi học hôm nay',value:1,goal:1,xp:10}]
  function claim(id:string){const quest=quests.find(item=>item.id===id);const next=[...claimed,id];setClaimed(next);localStorage.setItem(`mam-quests-${courseSlug}`,JSON.stringify({date:new Date().toISOString().slice(0,10),streak,claimed:next}));playLearningSound('reward');speakVietnamese(`Nhận thưởng thành công! Bé được cộng ${quest?.xp||0} điểm kinh nghiệm.`)}
  return <section className="mt-8 overflow-hidden rounded-[28px] border border-hairline bg-white shadow-sm"><header className="flex flex-wrap items-center justify-between gap-3 bg-gradient-to-r from-blue to-violet p-5 text-white"><div><p className="flex items-center gap-2 text-xs font-black uppercase tracking-wider text-yellow"><CalendarDays className="h-4 w-4"/>Nhiệm vụ hôm nay</p><h3 className="mt-1 text-2xl text-white">Mỗi ngày một bước sáng tạo</h3></div><div className="flex items-center gap-2 rounded-2xl bg-white/15 px-4 py-2 font-black"><Flame className="h-6 w-6 text-yellow"/>{streak} ngày liên tiếp</div></header><div className="grid gap-3 p-4 sm:p-5">{quests.map(q=>{const done=q.value>=q.goal,got=claimed.includes(q.id);return <article key={q.id} className="grid items-center gap-3 rounded-2xl bg-cream/70 p-4 sm:grid-cols-[auto_1fr_auto]"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white text-2xl shadow-sm">{q.icon}</span><div><div className="flex items-center justify-between gap-3"><strong>{q.title}</strong><span className="text-xs font-black text-blue">+{q.xp} XP</span></div><div className="mt-2 h-3 overflow-hidden rounded-full bg-white"><div className={`h-full rounded-full ${done?'bg-green':'bg-blue'}`} style={{width:`${Math.min(100,q.value/q.goal*100)}%`}}/></div><p className="mt-1 text-xs text-ink/55">{q.value}/{q.goal} hoàn thành</p></div><button type="button" disabled={!done||got} onClick={()=>claim(q.id)} className={`btn min-h-11 justify-center ${got?'border border-green bg-green-soft text-green':done?'btn-primary':'border border-hairline bg-white opacity-45'}`}>{got?<><CheckCircle2 className="h-4 w-4"/>Đã nhận</>:<><Gift className="h-4 w-4"/>Nhận thưởng</>}</button></article>})}</div><footer className="flex items-center gap-3 border-t border-hairline bg-yellow/10 px-5 py-4"><Trophy className="h-8 w-8 text-yellow"/><div><strong>Thử thách tuần: hoàn thành 5 bài</strong><p className="text-sm text-ink/60">Nhận huy hiệu Siêng năng và 150 XP</p></div><span className="ml-auto rounded-full bg-white px-3 py-1 text-sm font-black text-blue">{Math.min(completedCount,5)}/5</span></footer></section>
}
