import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

const pages={
  "ve-tranh-tu-y-tuong":{title:"Vẽ tranh từ ý tưởng cho trẻ em",label:"GÓC VẼ TRANH",desc:"Giúp bé biến những điều đang tưởng tượng thành một bức tranh độc đáo, sau đó tự thêm màu sắc và chi tiết của riêng mình.",icon:"🎨",prompts:["Chú mèo lái tàu vũ trụ","Thành phố nằm trên mây","Khu vườn của khủng long"],learn:"Quan sát · Màu sắc · Kể chuyện bằng hình ảnh"},
  "tao-truyen-cho-be":{title:"Tạo truyện cho bé từ ý tưởng riêng",label:"GÓC KỂ CHUYỆN",desc:"Bé chọn nhân vật, nơi câu chuyện diễn ra và điều bất ngờ. Mỗi lựa chọn tạo nên một câu chuyện không trùng lặp.",icon:"📖",prompts:["Chuyến đi đầu tiên của Mây","Bạn rồng không biết phun lửa","Chiếc chìa khóa dưới đáy biển"],learn:"Ngôn ngữ · Cảm xúc · Tư duy trình tự"},
  "lap-trinh-cho-tre-em":{title:"Học lập trình bằng khối cho trẻ em",label:"GÓC LẬP TRÌNH",desc:"Xếp khối lệnh trực quan để nhân vật di chuyển, phát âm thanh và tương tác — không cần biết gõ mã.",icon:"🧩",prompts:["Đưa phi thuyền tới mặt trăng","Làm mèo nhảy khi chạm sao","Tạo mê cung tìm kho báu"],learn:"Logic · Giải quyết vấn đề · Thử và sửa"}
} as const;
type Slug=keyof typeof pages;
export function generateStaticParams(){return Object.keys(pages).map(slug=>({slug}))}
export async function generateMetadata({params}:{params:Promise<{slug:string}>}):Promise<Metadata>{const {slug}=await params;const page=pages[slug as Slug];return page?{title:page.title,description:page.desc,alternates:{canonical:`/cong-cu/${slug}`}}:{}}
export default async function ToolPage({params}:{params:Promise<{slug:string}>}){const {slug}=await params;const page=pages[slug as Slug];if(!page)notFound();return <main className="tool-page"><header className="topbar wrap"><Link href="/" className="logo"><span>✺</span> Mầm Sáng Tạo</Link><Link className="header-cta" href="/#cong-cu">Xem mọi công cụ →</Link></header><section className="tool-hero wrap"><div><span className="kicker">{page.label}</span><h1>{page.title}</h1><p>{page.desc}</p><a className="primary" href="#bat-dau">Bắt đầu miễn phí →</a></div><div className="tool-big-icon">{page.icon}<i>✦</i></div></section><section id="bat-dau" className="tool-work"><div className="wrap"><span className="kicker">GỢI Ý ĐỂ BẮT ĐẦU</span><h2>Chọn một ý tưởng hoặc viết điều bé thích</h2><div className="prompt-cards">{page.prompts.map(x=><Link href={`/?idea=${encodeURIComponent(x)}#thu-ngay`} key={x}><span>{page.icon}</span><b>{x}</b><small>Dùng ý tưởng này →</small></Link>)}</div><p className="learning"><b>Bé sẽ rèn luyện:</b> {page.learn}</p></div></section><section className="seo-copy wrap"><h2>Sáng tạo là một cách học tự nhiên</h2><p>Mỗi dự án bắt đầu bằng trí tưởng tượng của trẻ. Thay vì chỉ xem nội dung có sẵn, bé chủ động lựa chọn, thử nghiệm và tạo nên một sản phẩm có thể chia sẻ với gia đình.</p><p>Hoạt động được thiết kế cho trẻ từ 6 đến 12 tuổi, có thể dùng tại nhà hoặc trong lớp học với sự đồng hành của người lớn.</p><Link href="/">← Trở về Xưởng sáng tạo</Link></section></main>}
