export const COURSES = [
  { slug: 'co-vua-cho-be', icon: '♟️', title: 'Cờ vua nhập môn', age: '6–10 tuổi', duration: '8 bài · 10 phút/bài', color: 'bg-yellow/20', description: 'Nhận biết quân cờ, luật di chuyển và những nước chiếu hết đầu tiên.', lessons: ['Bàn cờ và hai đội quân', 'Cách quân Tốt di chuyển', 'Xe, Tượng và Hậu', 'Mã nhảy chữ L', 'Vua và luật chiếu', 'Nhập thành an toàn', 'Đổi quân có lợi', 'Chiếu hết trong một nước'] },
  { slug: 'am-nhac-vui-nhon', icon: '🎵', title: 'Âm nhạc vui nhộn', age: '6–12 tuổi', duration: '6 bài · 12 phút/bài', color: 'bg-violet/15', description: 'Khám phá nhịp, cao độ và tự phối một giai điệu ngắn bằng tai nghe.', lessons: ['Nghe và vỗ theo nhịp', 'Nốt cao và nốt thấp', 'Làm quen bốn nhạc cụ', 'Tạo tiết tấu 4 nhịp', 'Phối giai điệu 8 bước', 'Biểu diễn tác phẩm của bé'] },
  { slug: 've-nhan-vat-hoat-hinh', icon: '🎨', title: 'Vẽ nhân vật hoạt hình', age: '6–11 tuổi', duration: '7 bài · 15 phút/bài', color: 'bg-coral/10', description: 'Dùng hình tròn, vuông và nét biểu cảm để tạo nhân vật độc đáo.', lessons: ['Nhân vật từ hình cơ bản', 'Đôi mắt biết kể chuyện', 'Vẽ năm cảm xúc', 'Trang phục và phụ kiện', 'Tạo dáng chuyển động', 'Chọn bảng màu', 'Hoàn thiện poster nhân vật'] },
  { slug: 'ke-chuyen-tu-tin', icon: '📖', title: 'Kể chuyện tự tin', age: '7–12 tuổi', duration: '6 bài · 15 phút/bài', color: 'bg-blue/10', description: 'Xây nhân vật, mở đầu hấp dẫn và kể một câu chuyện có cao trào.', lessons: ['Ai là nhân vật chính?', 'Chọn bối cảnh kỳ thú', 'Mở đầu bằng câu hỏi', 'Tạo thử thách bất ngờ', 'Kết thúc đáng nhớ', 'Kể chuyện trước gia đình'] },
  { slug: 'lap-trinh-game-dau-tien', icon: '🧩', title: 'Game đầu tiên của bé', age: '8–12 tuổi', duration: '8 bài · 15 phút/bài', color: 'bg-green/15', description: 'Hiểu lệnh, sự kiện và vòng lặp qua một trò chơi điều khiển nhân vật.', lessons: ['Lệnh và thứ tự', 'Di chuyển nhân vật', 'Sự kiện bàn phím', 'Chạm và ghi điểm', 'Chướng ngại vật', 'Âm thanh trong game', 'Thêm màn chơi', 'Chia sẻ game đầu tiên'] },
] as const

export type Course = (typeof COURSES)[number]
