export type Lesson = { title: string; goal: string; steps: readonly string[]; practice: string; parentTip: string }

function lesson(title: string, goal: string, explore: string, practice: string, parentTip: string): Lesson {
  return { title, goal, steps: [`Khởi động: cùng bé nhắc lại điều đã biết về “${title}”.`, `Khám phá: ${explore}`, `Thử lại: để bé tự giải thích bằng lời hoặc làm một ví dụ khác.`], practice, parentTip }
}

export const COURSES = [
  { slug: 'co-vua-cho-be', icon: '♟️', title: 'Cờ vua nhập môn', age: '6–10 tuổi', duration: '8 bài · 10 phút/bài', color: 'bg-yellow/20', description: 'Nhận biết quân cờ, luật di chuyển và những nước chiếu hết đầu tiên.', lessons: [
    lesson('Bàn cờ và hai đội quân', 'Nhận biết bàn cờ 8×8, ô sáng/tối và vị trí ban đầu.', 'Đặt ô sáng ở góc phải, xếp Xe–Mã–Tượng–Hậu–Vua rồi hàng Tốt phía trước.', 'Trộn 16 quân trắng và nhờ bé xếp đúng trong 2 phút.', 'Không cần nhớ tên tọa độ ngay; ưu tiên xếp đúng hình và vị trí.'),
    lesson('Cách quân Tốt di chuyển', 'Biết Tốt đi thẳng, ăn chéo và không đi lùi.', 'Cho một quân Tốt tiến từng ô; ở nước đầu bé thử chọn đi một hoặc hai ô.', 'Đặt ba quân đối diện và hỏi Tốt có thể đi hay ăn quân nào.', 'Dùng đồ vật nhỏ thay quân cờ nếu bé chưa quen bàn cờ.'),
    lesson('Xe, Tượng và Hậu', 'Phân biệt đường đi thẳng, chéo và kết hợp của ba quân.', 'Cho Xe chạy như dấu cộng, Tượng như chữ X, Hậu kết hợp cả hai nhưng không nhảy qua quân.', 'Đặt một quân ở giữa bàn và đếm số ô nó có thể tới.', 'Hỏi “đường có bị chặn không?” trước mỗi nước đi.'),
    lesson('Mã nhảy chữ L', 'Hiểu Mã đi 2 ô một hướng rồi 1 ô vuông góc và có thể nhảy.', 'Dùng ngón tay vẽ chữ L trên bàn cờ, đánh dấu tối đa tám điểm đến của Mã.', 'Đặt Mã ở góc rồi giữa bàn, so sánh số nước đi.', 'Cho bé đọc nhịp “hai rồi một” khi di chuyển Mã.'),
    lesson('Vua và luật chiếu', 'Biết Vua đi một ô và phải thoát khỏi vùng bị tấn công.', 'Tạo một tình huống chiếu đơn giản; thử ba cách: chạy Vua, chắn đường hoặc bắt quân chiếu.', 'Đặt Xe chiếu Vua và nhờ bé tìm ít nhất hai cách phòng thủ.', 'Nhắc bé không được bắt Vua; ván cờ dừng ở chiếu hết.'),
    lesson('Nhập thành an toàn', 'Biết điều kiện và thao tác nhập thành gần hoặc xa.', 'Kiểm tra Vua và Xe chưa đi, đường trống, Vua không bị chiếu hay đi qua ô bị chiếu.', 'Xếp hai tình huống, một hợp lệ và một bị chắn, để bé chọn.', 'Thực hiện Vua trước hai ô rồi đưa Xe qua để tránh nhầm.'),
    lesson('Đổi quân có lợi', 'Làm quen giá trị tương đối và quyết định đổi quân.', 'Dùng điểm Tốt 1, Mã/Tượng 3, Xe 5, Hậu 9 để so sánh hai bên sau trao đổi.', 'Cho ba tình huống đổi quân và để bé cộng điểm trước khi chọn.', 'Khen cách giải thích, không chỉ kết quả; thế cờ đôi khi quan trọng hơn điểm.'),
    lesson('Chiếu hết trong một nước', 'Quan sát ô thoát của Vua và tìm nước kết thúc.', 'Kiểm tra lần lượt: quân nào chiếu, Vua chạy được không, có thể chắn hoặc bắt quân chiếu không.', 'Dựng ba thế Hậu–Vua hoặc Xe–Vua đơn giản để bé tìm nước chiếu hết.', 'Nếu khó, cho bé khoanh các ô Vua có thể chạy trước.'),
  ] },
  { slug: 'am-nhac-vui-nhon', icon: '🎵', title: 'Âm nhạc vui nhộn', age: '6–12 tuổi', duration: '6 bài · 12 phút/bài', color: 'bg-violet/15', description: 'Khám phá nhịp, cao độ và tự phối một giai điệu ngắn bằng tai nghe.', lessons: [
    lesson('Nghe và vỗ theo nhịp', 'Giữ nhịp đều và nhận ra phách mạnh.', 'Mở một đoạn nhạc chậm, đếm 1–2–3–4 và vỗ mạnh ở số 1.', 'Vỗ một mẫu bốn nhịp để người thân bắt chước rồi đổi vai.', 'Dùng chân bước đều nếu bé khó vừa nghe vừa vỗ.'),
    lesson('Nốt cao và nốt thấp', 'Phân biệt cao độ bằng tai và giọng hát.', 'Phát hai âm cách xa nhau; bé chỉ tay lên khi âm cao và xuống khi âm thấp.', 'Tạo chuỗi 5 âm lên–xuống và vẽ đường biểu diễn cao độ.', 'Không chê giọng hát; mục tiêu là nghe và phân biệt.'),
    lesson('Làm quen bốn nhạc cụ', 'Nhận biết màu âm piano, chuông, robot và sáo.', 'Nghe từng nhạc cụ cùng một nốt rồi mô tả bằng từ như sáng, mềm, vang, điện tử.', 'Chọn nhạc cụ phù hợp cho cảnh ngủ, lễ hội, vũ trụ và khu rừng.', 'Không có đáp án duy nhất; hỏi bé vì sao chọn màu âm đó.'),
    lesson('Tạo tiết tấu 4 nhịp', 'Ghép âm và khoảng lặng thành mẫu ngắn.', 'Dùng ký hiệu ♪ cho âm và – cho nghỉ, thử các mẫu ♪♪–♪ và ♪–♪–.', 'Tạo ba tiết tấu bốn ô rồi chọn mẫu dễ nhớ nhất.', 'Khoảng lặng cũng là âm nhạc; đừng bật đầy mọi ô.'),
    lesson('Phối giai điệu 8 bước', 'Tạo câu nhạc có mở đầu, phát triển và kết thúc.', 'Bắt đầu bằng 3 nốt, lặp có thay đổi ở giữa và kết ở nốt tạo cảm giác ổn định.', 'Dùng Xưởng Âm nhạc để bật 8 ô, chọn nhạc cụ và tốc độ.', 'Nghe ít nhất hai lần trước khi chỉnh từng nốt.'),
    lesson('Biểu diễn tác phẩm của bé', 'Giới thiệu và trình diễn giai điệu tự tin.', 'Đặt tên tác phẩm, nói cảm xúc muốn truyền tải rồi đếm nhịp trước khi phát.', 'Biểu diễn cho gia đình và hỏi người nghe tưởng tượng khung cảnh nào.', 'Chỉ góp ý một điều cụ thể và luôn bắt đầu bằng điểm bé làm tốt.'),
  ] },
  { slug: 've-nhan-vat-hoat-hinh', icon: '🎨', title: 'Vẽ nhân vật hoạt hình', age: '6–11 tuổi', duration: '7 bài · 15 phút/bài', color: 'bg-coral/10', description: 'Dùng hình tròn, vuông và nét biểu cảm để tạo nhân vật độc đáo.', lessons: [
    lesson('Nhân vật từ hình cơ bản', 'Biến tròn, vuông, tam giác thành đầu và thân.', 'Chồng các hình lớn trước, thêm tay chân bằng nét đơn rồi mới thêm chi tiết.', 'Vẽ ba nhân vật, mỗi nhân vật bắt đầu từ một hình khác nhau.', 'Không sửa nét của bé; hỏi hình nào tạo cảm giác nhanh, mạnh hoặc mềm.'),
    lesson('Đôi mắt biết kể chuyện', 'Dùng kích thước, hướng nhìn và lông mày tạo tính cách.', 'So sánh mắt tròn to, mắt hẹp và mắt nhìn lệch; thêm lông mày để đổi cảm xúc.', 'Vẽ cùng một khuôn mặt với ba kiểu mắt khác nhau.', 'Che miệng nhân vật và đoán cảm xúc chỉ qua mắt.'),
    lesson('Vẽ năm cảm xúc', 'Thể hiện vui, buồn, giận, sợ và ngạc nhiên.', 'Quan sát hướng cong của miệng, độ mở mắt và tư thế vai cho từng cảm xúc.', 'Chia giấy thành 5 ô và vẽ nhân vật phản ứng với 5 tình huống.', 'Cho bé soi gương làm biểu cảm trước khi vẽ.'),
    lesson('Trang phục và phụ kiện', 'Dùng quần áo, màu và đồ vật để kể nghề nghiệp/sở thích.', 'Chọn một vai như phi hành gia hoặc đầu bếp, tìm ba chi tiết nhận diện rõ nhất.', 'Thiết kế hai bộ trang phục cho cùng một nhân vật ở hai nhiệm vụ.', 'Ưu tiên ba chi tiết lớn thay vì quá nhiều chi tiết nhỏ.'),
    lesson('Tạo dáng chuyển động', 'Dùng đường hành động và khớp đơn giản để tạo dáng.', 'Vẽ một đường cong thể hiện hướng chuyển động, đặt đầu–vai–hông rồi nối tay chân.', 'Vẽ nhân vật chạy, nhảy và bay trên ba khung nhỏ.', 'Nếu dáng cứng, thử diễn tư thế bằng cơ thể trước.'),
    lesson('Chọn bảng màu', 'Chọn 3–5 màu hài hòa và tạo điểm nhấn.', 'Chọn một màu chính, một màu phụ, màu sáng/tối và một màu nhấn nhỏ.', 'Tô hai phiên bản: ấm áp và mát mẻ, rồi so sánh cảm xúc.', 'Để vùng trắng giúp tranh dễ nhìn, không cần tô kín tất cả.'),
    lesson('Hoàn thiện poster nhân vật', 'Kết hợp nhân vật, tên, khẩu hiệu và nền đơn giản.', 'Đặt nhân vật lớn nhất, tên dễ đọc, thêm 2–3 biểu tượng kể sở thích.', 'Hoàn thiện poster A4 và giới thiệu nhân vật trong 30 giây.', 'Chụp/lưu tác phẩm trước khi chỉnh tiếp để bé thấy quá trình tiến bộ.'),
  ] },
  { slug: 'ke-chuyen-tu-tin', icon: '📖', title: 'Kể chuyện tự tin', age: '7–12 tuổi', duration: '6 bài · 15 phút/bài', color: 'bg-blue/10', description: 'Xây nhân vật, mở đầu hấp dẫn và kể một câu chuyện có cao trào.', lessons: [
    lesson('Ai là nhân vật chính?', 'Tạo nhân vật có mong muốn, điểm mạnh và điều còn sợ.', 'Hoàn thành ba câu: bạn ấy muốn…, giỏi…, nhưng lo lắng về….', 'Viết thẻ nhân vật 5 dòng và vẽ một biểu tượng đại diện.', 'Nhân vật thú vị không cần hoàn hảo; điểm yếu tạo cơ hội trưởng thành.'),
    lesson('Chọn bối cảnh kỳ thú', 'Dùng giác quan để làm nơi chốn sống động.', 'Mô tả bối cảnh bằng thứ nhìn thấy, nghe thấy, ngửi thấy và có thể chạm.', 'Viết 4 câu về khu vườn trên mây hoặc thành phố dưới biển.', 'Hỏi “ở đó có điều gì không thể có ngoài đời?” để kích thích tưởng tượng.'),
    lesson('Mở đầu bằng câu hỏi', 'Tạo câu mở đầu khiến người nghe tò mò.', 'Thử mở bằng “Điều gì sẽ xảy ra nếu…?”, một âm thanh lạ hoặc một bí mật.', 'Viết ba mở đầu cho cùng câu chuyện rồi đọc to để chọn.', 'Mở đầu nên ngắn và tạo một câu hỏi trong đầu người nghe.'),
    lesson('Tạo thử thách bất ngờ', 'Xây trở ngại buộc nhân vật phải lựa chọn.', 'Đặt mục tiêu của nhân vật, thêm vật cản và cho hai cách giải quyết có đánh đổi.', 'Viết đoạn “Nhưng đúng lúc đó…” và đưa vào một bất ngờ hợp lý.', 'Bất ngờ vẫn cần liên quan điều đã xuất hiện trước đó.'),
    lesson('Kết thúc đáng nhớ', 'Khép lại thử thách và cho thấy nhân vật thay đổi.', 'Trả lời ba câu: vấn đề được giải quyết ra sao, nhân vật học gì, hình ảnh cuối là gì.', 'Viết hai kết thúc vui/bất ngờ rồi chọn kết phù hợp nhất.', 'Không cần giải thích mọi thứ; một hình ảnh cuối rõ thường mạnh hơn.'),
    lesson('Kể chuyện trước gia đình', 'Luyện giọng, ánh mắt và nhịp nghỉ khi trình bày.', 'Đánh dấu chỗ nói chậm, nhấn giọng và dừng; tập kể bằng từ khóa thay vì đọc thuộc.', 'Kể câu chuyện 2 phút, sau đó hỏi người nghe nhớ chi tiết nào nhất.', 'Không ngắt lời sửa giữa lúc bé kể; ghi góp ý để trao đổi sau.'),
  ] },
  { slug: 'lap-trinh-game-dau-tien', icon: '🧩', title: 'Game đầu tiên của bé', age: '8–12 tuổi', duration: '8 bài · 15 phút/bài', color: 'bg-green/15', description: 'Hiểu lệnh, sự kiện và vòng lặp qua một trò chơi điều khiển nhân vật.', lessons: [
    lesson('Lệnh và thứ tự', 'Hiểu máy tính thực hiện từng lệnh theo thứ tự.', 'Xếp ba thẻ “đi tới–xoay–nói” theo nhiều thứ tự và quan sát kết quả khác nhau.', 'Trong Xưởng Lập trình, ghép 4 khối để nhân vật đi rồi chào.', 'Yêu cầu bé dự đoán trước khi bấm Chạy.'),
    lesson('Di chuyển nhân vật', 'Điều khiển vị trí bằng trục ngang và dọc.', 'Thử đi tới/lùi/lên/xuống, quan sát thay đổi vị trí sau mỗi lệnh.', 'Dẫn nhân vật từ góc trái tới một ngôi sao bằng ít lệnh nhất.', 'Cho phép thử sai; tối ưu chỉ sau khi game đã chạy đúng.'),
    lesson('Sự kiện bàn phím', 'Hiểu sự kiện là tín hiệu bắt đầu hành động.', 'Gán phím trái/phải/lên cho các chuyển động và kiểm tra từng phím.', 'Tạo bộ điều khiển bốn hướng và mời người khác thử.', 'Nhắc bé mỗi phím nên có hành vi dễ đoán.'),
    lesson('Chạm và ghi điểm', 'Phát hiện va chạm và cập nhật biến điểm.', 'Khi nhân vật chạm vật phẩm, cộng 1 điểm rồi đưa vật phẩm sang vị trí mới.', 'Tạo game nhặt 5 ngôi sao và hiển thị thông báo chiến thắng.', 'Kiểm tra điểm chỉ cộng một lần cho mỗi lần chạm.'),
    lesson('Chướng ngại vật', 'Tạo luật thua hoặc quay lại khi va chạm.', 'Đặt đá/gỗ trên đường chạy; khi chạm, giảm điểm hoặc trở về đầu.', 'Thiết kế đường chạy có hai chướng ngại và khoảng cách vừa sức.', 'Tăng độ khó từng chút, tránh làm màn đầu quá khó.'),
    lesson('Âm thanh trong game', 'Dùng âm thanh làm phản hồi cho hành động.', 'Chọn âm ngắn khi nhặt vật phẩm, âm thấp khi va chạm và nhạc nền nhẹ.', 'Thêm ít nhất hai hiệu ứng âm thanh khác nhau vào game.', 'Âm thanh nên ngắn và âm lượng vừa để không gây mệt.'),
    lesson('Thêm màn chơi', 'Chuyển sang thử thách mới khi đạt mục tiêu.', 'Đặt điều kiện đủ điểm, đổi nền, vị trí vật phẩm và tăng nhẹ tốc độ.', 'Tạo màn 2 khác màn 1 bằng ít nhất hai yếu tố.', 'Giữ cách điều khiển nhất quán giữa các màn.'),
    lesson('Chia sẻ game đầu tiên', 'Kiểm thử, mô tả luật và tiếp nhận góp ý.', 'Chơi thử ba lần, kiểm tra bắt đầu–thắng–thua rồi viết hướng dẫn hai câu.', 'Mời một người chơi không cần trợ giúp và ghi lại một điểm cần cải thiện.', 'Hỏi người chơi “chỗ nào chưa rõ?” thay vì chỉ hỏi có vui không.'),
  ] },
] as const

export type Course = (typeof COURSES)[number]
